source "https://rubygems.org"

ruby "3.2.5"

gem "rails", "~> 8.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "jwt", "~> 2.8"
gem "rack-cors", "~> 2.0"
gem "bootsnap", require: false
gem "mqtt", "~> 0.6"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "dotenv-rails"
end

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end
